from .mantel import Mantel
from .anosim import anosim
from .simper import simper
from .procrust_test import procrustes_test
from .fourthcorner import corner4
from .rlq import rlq
from .rda import rda
from .cca import cca
from .ccor import ccor